### ISSUE TITLE
[Bug report] The CI cannot be triggered automatically when a backport PR is created by github bot

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1282]
### Describe what's wrong

When a backport PR is created by github bot, it cannot automatically trigger the CI, we have to manually close and reopen the PR to trigger it, it's not so convenient.

### Error message and/or stacktrace

No

### How to reproduce

Just create a backport PR can trigger this issue.

**Comment by BWbwchen** [comment]
Hi,

After researching the solution to this issue, I found that this issue is caused by the default setting of GitHub, which prevents triggering a workflow from a workflow.

The solution might be to set the `token` [input](https://github.com/marketplace/actions/github-cherry-pick-action#action-inputs) used in the `github-cherry-pick-action` in [auto-cherry-pick.yml](https://github.com/datastrato/gravitino/blob/87461a71b18740eec6fa4944b7ced64279216b95/.github/workflows/auto-cherry-pick.yml#L19-L26) to some [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token), instead of the default token, `GITHUB_TOKEN`.

According to the official GitHub action [documentation](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow), triggering a workflow from a workflow that is generated by the repository's `GITHUB_TOKEN` is prohibited by default.
> When you use the repository's `GITHUB_TOKEN` to perform tasks, events triggered by the `GITHUB_TOKEN`, with the exception of `workflow_dispatch` and `repository_dispatch`, will not create a new workflow run.

To solve this issue, the documentation gives us some methods: 
> If you do want to trigger a workflow from within a workflow run, you can use a GitHub App installation access token or a personal access token instead of `GITHUB_TOKEN` to trigger events that require a token.

The auto-cherry-pick workflow uses `carloscastrojumo/github-cherry-pick-action@v1.0.9` to push a backport PR and the default token that this action used is `GITHUB_TOKEN` as shown in its [documentation](https://github.com/marketplace/actions/github-cherry-pick-action#action-inputs). Thus, we can set the token that `github-cherry-pick-action` use to some [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) to solve this issue.

Tim

**Comment by jerryshao** [comment]
Thanks a lot @BWbwchen for your investigation, greatly appreciated. Let me see how to use PAT to solve this issue.

**Comment by BWbwchen** [comment]
It seems that we can use [the PAT of the organization](https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization#restricting-access-by-personal-access-tokens-classic).

I can help to contribute to the auto-cherry-pick workflow file. Since I don't have permission to set the PAT for the organization, I need your help to set a PAT for solving this issue.

**Comment by jerryshao** [comment]
Thanks a lot @BWbwchen , let me check how to create the organization PAT. It would be greatly helpful if you can help improve the auto-cherry-pick workflow.
