### ISSUE TITLE
[Improvement] Use of non-static initializers in `MysqlDatabaseOperations.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1947]
### What would you like to be improved?

Non-static initializers, also known as instance initializers, are rarely used and can be confusing. These are used in SYS_MYSQL_DATABASE_NAMES and in where a  new JdbcSchema.Builder() is created in load.

### How should we improve?

Initialize inside a constructor/local variable?

**Comment by NIRMALraki** [comment]
Initializing directly using local variable would be better.
Reasons: - It will be clear at a glance otherwise variable needs to found and again search for the constructor is required to know the default value.
- If in case in future if add more constructors to the class it should be added to all of them individually. 

Please feel free to discuss or ask for further clarification. Looking forward to contributing to this improvement!
