### ISSUE TITLE
[Improvement] Potential SQL injection point in generateDropDatabaseSql

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2179]
### What would you like to be improved?

The database name is passed into generateDropDatabaseSql and is passed on to executeQuery without checking or validating it's contents.[](url)

### How should we improve?

Verify the database name before calling executeQuery.

**Comment by henrybear327** [comment]
Hello @justinmclean, 

I would like to work on this issue, but may I request more hints on how to go about fixing this issue?

Thank you!

**Comment by justinmclean** [comment]
These links may help:
https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection
https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html

In this case, I would check if the name is in an expected format with a regular expression or similar.

**Comment by mchades** [comment]
Has the issue been resolved after merging #3053?

**Comment by zivali** [comment]
I saw https://github.com/datastrato/gravitino/pull/3053 which originally seems to fix this issue is causing bug report for listing MySQL schema '//' in https://github.com/datastrato/gravitino/issues/3101. So currently we do not `applyCapabilitiesOnName` when dropping schema [#3126](https://github.com/datastrato/gravitino/pull/3126/files#diff-653475244e57b070f2c28c3911878c636bef40b01c7d66d085834a15b2379fc7R68-R71).
But '/' is not a classic character in [MySQL identifier](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html).

Should we still verify the naming before dropping using the capability framework? 
If so, there may be other bug reports which request supports for special characters in the future.

**Comment by mchades** [comment]
> But '/' is not a classic character in [MySQL identifier](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html).

Although `/` is not a classic character in MySQL, there are indeed real user scenarios that require it to be included in the database name, so we need to allow users to operate it.

> Should we still verify the naming before dropping using the capability framework?
> If so, there may be other bug reports which request supports for special characters in the future.
 
Is there any other way to prevent potential SQL injection in `generateDropDatabaseSql` other than checking the name? (such as [prepared-statements-with-parameterized-queries](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html#defense-option-1-prepared-statements-with-parameterized-queries)?)

If not, I think we can verify the naming before dropping using the capability framework firstly to resolve this issue. If there are other users who need to use special characters in real scenarios, we will gradually relax restrictions or make the name spec capability configurable for users. WDYT?

**Comment by zivali** [comment]
I tested `generateDropDatabaseSql` with prepared statements. It can indeed prevent sql injection as shown in the example. I think we can switch to use this approach as well. Thanks for the suggestion! :)

**Comment by zivali** [comment]
Prepared statement seems to be designed to handle data values, not for SQL identifiers like table names or database names.
So when creating and deleting table/database, most JDBC doesn't support using prepared statement e.g. [MySQL](https://stackoverflow.com/questions/9252392/mysql-drop-table-as-preparedstatement-not-working-for-me)
I think we may still need to validate the naming. Do Gravitino collects user logs so that we may know what are some special characters that are currently in use by users?

**Comment by mchades** [comment]
This regular expression already contains the special characters that are known to be used by the user
https://github.com/datastrato/gravitino/blob/a09420dd90a413a4f4944fc628286d20f9950d1c/core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java#L87-L97

**Comment by zivali** [comment]
Got it, thanks! I think we can add separate regex name pattern for the 3 JDBC catalog and validate naming when creating and dropping table/database. What do you think? :)
