### ISSUE TITLE
[Subtask] Fix method-hidden Pylint rule for client-python

### ISSUE THREAD

**Issue by noidname01** [datastrato/gravitino#3768]
### Describe the subtask

* According to this [doc](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/method-hidden.html), the name of attribute in class should not be as same as the method in the class, please try to rename one of them.

### Parent issue

#3560

**Comment by featherchen** [comment]
I am working on this issue, the reason is that the method name and attribute name in some classes is the same, e.g. class `RenameCatalog` in `catalog_change.py`.

For more details about this pylint checker, please see: https://pylint.readthedocs.io/en/latest/user_guide/messages/error/method-hidden.html
